export const errorHandler = (api) => (req, res, next) => {
  api(req, res, next).catch(
    (error) => {
      console.log(`ğŸ’¥ Oops! Something went wrong in: ${req.url}`, error);
      res.status(500).json({ message: "ğŸ’¥ Oops! Something went wrong!", error: error.message });
      return next();
    }
  );
};

export const globalErrorHandler = (error) => {
  console.log("ğŸ’¥ Global Error Handler:", error.message);
  return ({ message: "ğŸ’¥ Internal Server Error", error: error.message });
};